# Day 1 - Session 1: Introduction to R and R Basics

### Learning Objectives
- Learn basic R syntax and operations
- Know fundamental R classes and data types
- Work with basic data structures

## 1. Basic R Syntax and Operations

### 1.1 R as a Calculator

In [ ]:
# Basic arithmetic operations
5 + 3      # Addition
10 - 4     # Subtraction
6 * 7      # Multiplication
20 / 4     # Division
2^3        # Exponentiation
17 %% 5    # Modulo (remainder)
17 %/% 5   # Integer division

Take advantage of `#` to add comments. Everything after `#` on a line is ignored by R.

### 1.2 Creating Variables

Variables store values for later use. Use `<-` or `=` for assignment.

In [7]:
# Creating variables
x <- 10
y <- 5
z <- x + y

# Display the result
print(z)
z  # Simply typing the variable name also displays it

[1] 15

[1] 15

Variable names:

- Must start with a letter
- Can contain letters, numbers, dots, and underscores
- Are case-sensitive

In [6]:
my_variable <- 100
MyVariable <- 200
my.variable <- 300

print(my_variable)  # Different from MyVariable

[1] 100

## 2. R Classes and Data Types

R has several basic data types:
- **numeric**: Numbers (integers and decimals)
  - **integer**: Whole numbers (no decimal points)
- **character**: Text strings
- **factor**: Categorical data (can be numbers or characters)
- **logical**: TRUE or FALSE

In [10]:
# Numeric
height <- 175.5
class(height)

# Character
name <- "Alice"
class(name)

# Logical
is_student <- TRUE
class(is_student)

# Integer (use L suffix)
count <- 42L
class(count)

[1] "numeric"

[1] "character"

[1] "logical"

[1] "integer"

Another way to assess the class of an R object is to use the `typeof()` function, which provides more detailed information about the internal storage mode of the object.

In [11]:
# Check the type of any object
typeof(height)
typeof(name)
typeof(is_student)

[1] "double"

[1] "character"

[1] "logical"

It is also possible to convert between data types via functions like `as.numeric()`, `as.character()`, `as.factor()`, and `as.logical()`. 

Be sure that change makes sense (e.g., converting characters to numeric will result in `NA` if the characters do not represent valid numbers) and that you understand how R handles such conversions (e.g. factors to numeric, by default, will give you the number corresponding to the observed level in factor).

In [13]:
# Converting between types
x <- "123"
print(class(x))

x_numeric <- as.numeric(x)
print(class(x_numeric))

# Converting numeric to character
y <- 456
y_char <- as.character(y)
print(class(y_char))

# Converting factor directly to numeric
x = factor(c("red", "blue", "green", "blue"))
as.numeric(x)

[1] "character"
[1] "numeric"
[1] "character"

[1] 3 1 2 1

## 3. Data Structures

### 3.1 Vectors

Vectors are the most basic data structure in R. They contain elements of the same type.

In [ ]:
# Creating vectors with c() function
ages <- c(25, 32, 28, 45, 38)
names <- c("Alice", "Bob", "Charlie", "Diana", "Eve")
is_phd <- c(TRUE, TRUE, FALSE, TRUE, FALSE)

print(ages)
print(names)

If you want to create a vector containing a sequence of numbers (e.g. from 1 to 10), instead of typing all the number, you can use the `:` operator or the `seq()` function:

In [ ]:
# Sequences
seq1 <- 1:10          # Simple sequence
seq2 <- seq(0, 100, by=10)  # Sequence with step
seq3 <- seq(0, 1, length.out=11)  # Sequence with length

print(seq1)
print(seq2)
print(seq3)

In [44]:
?seq

seq                    package:base                    R Documentation

_S_e_q_u_e_n_c_e _G_e_n_e_r_a_t_i_o_n

_D_e_s_c_r_i_p_t_i_o_n:

     Generate regular sequences.  'seq' is a standard generic with a
     default method.  'seq.int' is a primitive which can be much faster
     but has a few restrictions.  'seq_along' and 'seq_len' are very
     fast primitives for two common cases.

_U_s_a_g_e:

     seq(...)

     ## Default S3 method:
     seq(from = 1, to = 1, by = ((to - from)/(length.out - 1)),
         length.out = NULL, along.with = NULL, ...)

     seq.int(from, to, by, length.out, along.with, ...)

     seq_along(along.with)
     seq_len(length.out)

_A_r_g_u_m_e_n_t_s:

     ...: arguments passed to or from methods.

from, to: the starting and (maximal) end values of the sequence.  Of
          length '1' unless just 'from' is supplied as an unnamed
          argument.

      by: number: increment of the sequence.

length.out: desired length of the sequence.  A non-negative number,
          which for 'seq' and 'seq.int' will be rounded up if
          fractional.

along.with: take the length from the length of this argument.

_D_e_t_a_i_l_s:

     Numerical inputs should all be finite (that is, not infinite,
     'NaN' or 'NA').

     The interpretation of the unnamed arguments of 'seq' and 'seq.int'
     is _not_ standard, and it is recommended always to name the
     arguments when programming.

     'seq' is generic, and only the default method is described here.
     Note that it dispatches on the class of the *first* argument
     irrespective of argument names.  This can have unintended
     consequences if it is called with just one argument intending this
     to be taken as 'along.with': it is much better to use 'seq_along'
     in that case.

     'seq.int' is an internal generic which dispatches on methods for
     '"seq"' based on the class of the first supplied argument (before
     argument matching).

     Typical usages are

     seq(from, to)
     seq(from, to, by= )
     seq(from, to, length.out= )
     seq(along.with= )
     seq(from)
     seq(length.out= )

     The first form generates the sequence 'from, from+/-1, ..., to'
     (identical to 'from:to').

     The second form generates 'from, from+by', ..., up to the sequence
     value less than or equal to 'to'.  Specifying 'to - from' and 'by'
     of opposite signs is an error.  Note that the computed final value
     can go just beyond 'to' to allow for rounding error, but is
     truncated to 'to'.  ('Just beyond' is by up to 1e-10 times
     'abs(from - to)'.)

     The third generates a sequence of 'length.out' equally spaced
     values from 'from' to 'to'.  ('length.out' is usually abbreviated
     to 'length' or 'len', and 'seq_len' is much faster.)

     The fourth form generates the integer sequence '1, 2, ...,
     length(along.with)'.  ('along.with' is usually abbreviated to
     'along', and 'seq_along' is much faster.)

     The fifth form generates the sequence '1, 2, ..., length(from)'
     (as if argument 'along.with' had been specified), _unless_ the
     argument is numeric of length 1 when it is interpreted as '1:from'
     (even for 'seq(0)' for compatibility with S).  Using either
     'seq_along' or 'seq_len' is much preferred (unless strict S
     compatibility is essential).

     The final form generates the integer sequence '1, 2, ...,
     length.out' unless 'length.out = 0', when it generates
     'integer(0)'.

     Very small sequences (with 'from - to' of the order of 10^{-14}
     times the larger of the ends) will return 'from'.

     For 'seq' (only), up to two of 'from', 'to' and 'by' can be
     supplied as complex values provided 'length.out' or 'along.with'
     is specified.  More generally, the default method of 'seq' will
     handle classed objects with methods for the 'Math', 'Ops' and
     'Summary' group generics.

     'seq.int', 'seq_along' and 'seq_len' are primitive.

_V_a_l_u_e:

     'seq.int' and the default method of 'seq' for numeric arguments
     return a vector of type '"integer"' or '"double"': programmers
     should not rely on which.

     'seq_along' and 'seq_len' return an integer vector, unless it is a
     _long vector_ when it will be double.

_R_e_f_e_r_e_n_c_e_s:

     Becker, R. A., Chambers, J. M. and Wilks, A. R. (1988) _The New S
     Language_.  Wadsworth & Brooks/Cole.

_S_e_e _A_l_s_o:

     The methods 'seq.Date' and 'seq.POSIXt'.

     ':', 'rep', 'sequence', 'row', 'col'.

_E_x_a_m_p_l_e_s:

     seq(0, 1, length.out = 11)
     seq(stats::rnorm(20)) # effectively 'along'
     seq(1, 9, by = 2)     # matches 'end'
     seq(1, 9, by = pi)    # stays below 'end'
     seq(1, 6, by = 3)
     seq(1.575, 5.125, by = 0.05)
     seq(17) # same as 1:17, or even better seq_len(17)

Additionally, to repeat elements, you can use the `rep()` function:

In [ ]:
# Repetition
rep1 <- rep(5, times=10)  # Repeat 5 ten times
rep2 <- rep(c(1,2,3), times=3)  # Repeat vector three times
rep3 <- rep(c(1,2,3), each=3)   # Repeat each element three times

print(rep1)
print(rep2)
print(rep3)

#### 3.1.1 Vector Operations

R allows element-wise operations on vectors of the same length. 

**Note:** If vectors are of different lengths, R recycles the shorter vector to match the length of the longer one.

In [20]:
# Arithmetic operations on vectors
v1 <- c(1, 2, 3, 4, 5)
v2 <- c(10, 20, 30, 40, 50)

v1 + v2  # Element-wise addition
v1 * v2  # Element-wise multiplication
v2 / v1  # Element-wise division

# !! Beware of this scenario !! #
y1 <- c(1,2,3)
y2 <- c(1,2,3,4,5,6)

y1 * y2  # R recycles y1 to match the length of y2

[1] 11 22 33 44 55

[1]  10  40  90 160 250

[1] 10 10 10 10 10

[1]  1  4  9  4 10 18

In [21]:
# Operations with scalars (recycling)
v1 * 10  # Multiply each element by 10
v1 + 5   # Add 5 to each element

[1] 10 20 30 40 50

[1]  6  7  8  9 10

There are several useful functions that allow you to extract relevant information from vectors:

In [22]:
# Useful vector functions
numbers <- c(12, 45, 23, 67, 34, 89, 21)

length(numbers)  # Number of elements
sum(numbers)     # Sum of all elements
mean(numbers)    # Average
median(numbers)  # Median
min(numbers)     # Minimum value
max(numbers)     # Maximum value
sd(numbers)      # Standard deviation
var(numbers)     # Variance

# Additional nugget - use the cat & paste functions for better output formatting
cat("The sum of numbers is:", sum(numbers), "\n")

[1] 7

[1] 291

[1] 41.57143

[1] 34

[1] 12

[1] 89

[1] 27.71195

[1] 767.9524

The sum of numbers is: 291

#### 3.1.2 Indexing Vectors

You can access and modify specific elements in a vector using their indexes 

**Note:** R uses 1-based indexing

In [26]:
fruits <- c("apple", "banana", "cherry", "date", "elderberry")

# Access by position
fruits[1]        # First element
fruits[3]        # Third element
fruits[c(1,3,5)] # Multiple elements
fruits[2:4]      # Range of elements

# Modify elements
fruits
fruits[2] <- "blueberry"
fruits

[1] "apple"

[1] "cherry"

[1] "apple"      "cherry"     "elderberry"

[1] "banana" "cherry" "date"

[1] "apple"      "banana"     "cherry"     "date"       "elderberry"

[1] "apple"      "blueberry"  "cherry"     "date"       "elderberry"

You can use the same logic to exclude elements by using a negative index:

In [ ]:
# Negative indexing (exclude elements)
fruits[-1]       # All except first
fruits[-c(2,4)]  # Exclude second and fourth

Finally, you can use logical vectors to get information from other vectors:

In [ ]:
# Logical indexing
ages <- c(25, 32, 28, 45, 38)
ages > 30        # Returns logical vector
ages[ages > 30]  # Filter values greater than

#### 3.1.3 Named Vectors
You can assign names to the elements of a vector using the `names()` function. This is helpful for easier indexing, particularly when you do not know the exact position of an element.

In [ ]:
# Vectors can have names
person_ages <- c(Alice=25, Bob=32, Charlie=28)
print(person_ages)

# Access by name
person_ages["Alice"]

# Get names
names(person_ages)

### 3.2 Matrices

Matrices are 2-dimensional arrays with elements of the same type.

In [27]:
# Creating matrices
mat1 <- matrix(1:12, nrow=3, ncol=4)
print(mat1)

# Fill by rows instead of columns
mat2 <- matrix(1:12, nrow=3, ncol=4, byrow=TRUE)
print(mat2)

     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12
     [,1] [,2] [,3] [,4]
[1,]    1    2    3    4
[2,]    5    6    7    8
[3,]    9   10   11   12

As in vectors, you can access and modify specific elements in a matrix using their row and column indexes:

In [28]:
# Matrix indexing: [row, column]
mat1[2, 3]      # Element in row 2, column 3
mat1[1, ]       # Entire first row
mat1[, 2]       # Entire second column
mat1[1:2, 2:3]  # Submatrix

[1] 8

[1]  1  4  7 10

[1] 4 5 6

     [,1] [,2]
[1,] 4    7
[2,] 5    8

`R` allows to collect information about matrices, the same way it does for vectors:

In [35]:
# Matrix info
dim(mat1)    # Dimensions
nrow(mat1)   # Number of rows
ncol(mat1)   # Number of columns
summary(mat1)  # Summary statistics

[1] 3 4

[1] 3

[1] 4

       V1            V2            V3            V4
 Min.   :1.0   Min.   :4.0   Min.   :7.0   Min.   :10.0
 1st Qu.:1.5   1st Qu.:4.5   1st Qu.:7.5   1st Qu.:10.5
 Median :2.0   Median :5.0   Median :8.0   Median :11.0
 Mean   :2.0   Mean   :5.0   Mean   :8.0   Mean   :11.0
 3rd Qu.:2.5   3rd Qu.:5.5   3rd Qu.:8.5   3rd Qu.:11.5
 Max.   :3.0   Max.   :6.0   Max.   :9.0   Max.   :12.0

### 3.2 Data Frames

Data frames are the most important data structure for data analysis - they're like spreadsheets!

In [30]:
# Creating a data frame
df <- data.frame(
  name = c("Alice", "Bob", "Charlie", "Diana"),
  age = c(25, 32, 28, 45),
  department = c("Biology", "Chemistry", "Physics", "Biology"),
  is_phd = c(TRUE, TRUE, FALSE, TRUE)
)

df

  name    age department is_phd
1 Alice   25  Biology     TRUE
2 Bob     32  Chemistry   TRUE
3 Charlie 28  Physics    FALSE
4 Diana   45  Biology     TRUE

Accessing and modifying elements in a data frame is similar to matrices.

In [31]:
# Accessing rows & columns
df[1, ]         # First row
df[c(1,3), ]    # First and third rows
df[, 2]           # By column number

  name  age department is_phd
1 Alice 25  Biology    TRUE

  name    age department is_phd
1 Alice   25  Biology     TRUE
3 Charlie 28  Physics    FALSE

[1] 25 32 28 45

Additionally, you can use the `$` operator to access columns by name.

**Note:** beware of spaces & special characters in column names when using the `$` operator. You should always aim at having column names:
- starting with a letter
- no spaces (use `_` or `.` instead)
- no special characters (e.g. `-`, `/`, `\`, etc.)

In [32]:
# Accessing columns
df$name           # Using $
df[["age"]]       # Using [[]]
df[, "department"] # Using [,]

[1] "Alice"   "Bob"     "Charlie" "Diana"

[1] 25 32 28 45

[1] "Biology"   "Chemistry" "Physics"   "Biology"

As with vectors, you can use several functions to get information about data frames:

In [ ]:
# Filtering rows
df[df$age > 30, ]              # Rows where age > 30
df[df$department == "Biology", ]  # Rows from Biology department

Finally, several other function used for matrices can be used with data frames, such as `nrow()`, `ncol()`, `dim()`, `head()`, and `tail()`.

In [ ]:
nrow(df) #Get number of rows
ncol(df) #Get number of columns
dim(df)  #Get dimensions

In [ ]:
head(df) #First few rows
tail(df) #Last few rows

In [ ]:
str(df)  # Structure of the data frame
summary(df)  # Summary statistics of the data frame

### 3.3 Lists

Lists can contain elements of different types, including single objects, vectors, matrices, data frames, and even other lists.

In [36]:
# Creating a list
my_list <- list(
  name = "John Doe",
  age = 35,
  scores = c(85, 92, 78),
  is_phd = TRUE
)

print(my_list)

$name
[1] "John Doe"

$age
[1] 35

$scores
[1] 85 92 78

$is_phd
[1] TRUE

In [37]:
# Accessing list elements
my_list$name        # By name using $
my_list[["age"]]    # By name using [[]]
my_list[[2]]        # By position
my_list[1]          # Returns a list with one element

[1] "John Doe"

[1] 35

[1] 35

$name
[1] "John Doe"

## 4. Practice Exercises

### Exercise 1: Basic Operations
Calculate the BMI for someone with weight 75 kg and height 1.80 m.
Formula: BMI = weight / height²

### Exercise 2: Vectors
Create a vector of temperatures in Celsius: 0, 10, 20, 30, 40
Convert them to Fahrenheit using the formula: F = (C * 9/5) + 32

### Exercise 3: Data Frame
Create a data frame with information about 5 experiments:
- experiment_id: 1 to 5
- temperature: 20, 25, 30, 35, 40
- success: TRUE, TRUE, FALSE, TRUE, FALSE

Then filter to show only successful experiments.

---

## 5. R Packages and Libraries

**R packages** are collections of functions, data, and documentation that extend R's capabilities. Think of them as plugins you add to R:
- **Base R** (package that comes by default) provides the backbone functions
- **Packages** add specialized tools for specific tasks

### 5.1. Where to Find R Packages?

**[1. CRAN (Comprehensive R Archive Network)](https://cran.r-project.org/)**
- Official repository with over 18,000 packages
- All packages tested and documented

**[2. Bioconductor](https://bioconductor.org/)**
- Specialized for bioinformatics and genomics
- Over 2,000 packages for biological data analysis
- Website: 

**[3. GitHub](https://github.com)**
- Development versions and specialized packages
- <u>Not always as stable as CRAN packages</u>

### 5.2 Installing Packages

To install packages in the R environment, use `install.packages()` to install from CRAN.

In [38]:
# Install a single package
install.packages("ggplot2")

# Install multiple packages at once
install.packages(c("dplyr", "tidyr", "readr"))

# Install from a specific CRAN mirror
install.packages("package_name", repos = "https://cran.rstudio.com/")

# Note: During installation, you may be asked to choose a CRAN mirror
# Select one close to your location for faster downloads

Installing package into 'C:/Users/asbarros/AppData/Local/R/win-library/4.5'
(as 'lib' is unspecified)

package 'ggplot2' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\asbarros\AppData\Local\Temp\RtmpCW1bof\downloaded_packages

Installing packages into 'C:/Users/asbarros/AppData/Local/R/win-library/4.5'
(as 'lib' is unspecified)

package 'dplyr' successfully unpacked and MD5 sums checked

Warning message:
"cannot remove prior installation of package 'dplyr'"
Warning message in file.copy(savedcopy, lib, recursive = TRUE):
"problem copying C:\Users\asbarros\AppData\Local\R\win-library\4.5\00LOCK\dplyr\libs\x64\dplyr.dll to C:\Users\asbarros\AppData\Local\R\win-library\4.5\dplyr\libs\x64\dplyr.dll: Permission denied"
Warning message:
"restored 'dplyr'"

package 'tidyr' successfully unpacked and MD5 sums checked
package 'readr' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\asbarros\AppData\Local\Temp\RtmpCW1bof\downloaded_packages

Installing package into 'C:/Users/asbarros/AppData/Local/R/win-library/4.5'
(as 'lib' is unspecified)

Warning message:
"package 'package_name' is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages"

### 5.3 Loading Packages

After installation, use `library()` or `require()` to load a package. **You must load packages in each R session!**

In [41]:
# Load a package (preferred method)
library(ggplot2)

`R` also provides some relevant functions to manage packages:

In [ ]:
# See all installed packages
# installed.packages()

# See loaded packages in current session
# search()

# Get help for a package
help(package = "ggplot2")

# Update all packages
# update.packages()

# Update a specific package
# update.packages("ggplot2")

# Remove a package
# remove.packages("package_name")

# Check package version
packageVersion("ggplot2")

[1] '4.0.1'

Documentation for package 'ggplot2'


		Information on package 'ggplot2'

Description:

Package:                      ggplot2
Title:                        Create Elegant Data Visualisations Using
                              the Grammar of Graphics
Version:                      4.0.1
Authors@R:                    c( person("Hadley", "Wickham", ,
                              "hadley@posit.co", role = "aut", comment
                              = c(ORCID = "0000-0003-4757-117X")),
                              person("Winston", "Chang", role = "aut",
                              comment = c(ORCID =
                              "0000-0002-1576-2126")), person("Lionel",
                              "Henry", role = "aut"), person("Thomas
                              Lin", "Pedersen", ,
                              "thomas.pedersen@posit.co", role =
                              c("aut", "cre"), comment = c(ORCID =
                              "0000-0002-5147-4711")), person("Kohske",
                              "Takahashi", role = "aut"),
                              person("Claus", "Wilke", role = "aut",
                              comment = c(ORCID =
                              "0000-0002-7470-9261")), person("Kara",
                              "Woo", role = "aut", comment = c(ORCID =
                              "0000-0002-5125-4188")),
                              person("Hiroaki", "Yutani", role = "aut",
                              comment = c(ORCID =
                              "0000-0002-3385-7233")), person("Dewey",
                              "Dunnington", role = "aut", comment =
                              c(ORCID = "0000-0002-9415-4582")),
                              person("Teun", "van den Brand", role =
                              "aut", comment = c(ORCID =
                              "0000-0002-9335-7468")), person("Posit,
                              PBC", role = c("cph", "fnd"), comment =
                              c(ROR = "03wc8by49")) )
Description:                  A system for 'declaratively' creating
                              graphics, based on "The Grammar of
                              Graphics". You provide the data, tell
                              'ggplot2' how to map variables to
                              aesthetics, what graphical primitives to
                              use, and it takes care of the details.
License:                      MIT + file LICENSE
URL:                          https://ggplot2.tidyverse.org,
                              https://github.com/tidyverse/ggplot2
BugReports:                   https://github.com/tidyverse/ggplot2/issues
Depends:                      R (>= 4.1)
Imports:                      cli, grDevices, grid, gtable (>= 0.3.6),
                              isoband, lifecycle (> 1.0.1), rlang (>=
                              1.1.0), S7, scales (>= 1.4.0), stats,
                              vctrs (>= 0.6.0), withr (>= 2.5.0)
Suggests:                     broom, covr, dplyr, ggplot2movies,
                              hexbin, Hmisc, hms, knitr, mapproj, maps,
                              MASS, mgcv, multcomp, munsell, nlme,
                              profvis, quantreg, quarto, ragg (>=
                              1.2.6), RColorBrewer, roxygen2, rpart, sf
                              (>= 0.7-3), svglite (>= 2.1.2), testthat
                              (>= 3.1.5), tibble, vdiffr (>= 1.0.6),
                              xml2
Enhances:                     sp
VignetteBuilder:              quarto
Config/Needs/website:         ggtext, tidyr, forcats,
                              tidyverse/tidytemplate
Config/testthat/edition:      3
Config/usethis/last-upkeep:   2025-04-23
Encoding:                     UTF-8
LazyData:                     true
RoxygenNote:                  7.3.3
Collate:                      'ggproto.R' 'ggplot-global.R' 'aaa-.R'
                              'aes-colour-fill-alpha.R'
                              'aes-evaluation.R' 'aes-group-order.R'
                              'aes-linetype-size-shape.R'
                              'aes-position.R' 'all-classes.R'
                              'compat-plyr.R' 'utilities.R' 'aes.R'
                              'annotation-borders.R'
                              'utilities-checks.R' 'legend-draw.R'
                              'geom-.R' 'annotation-custom.R'
                              'annotation-logticks.R' 'scale-type.R'
                              'layer.R' 'make-constructor.R'
                              'geom-polygon.R' 'geom-map.R'
                              'annotation-map.R' 'geom-raster.R'
                              'annotation-raster.R' 'annotation.R'
                              'autolayer.R' 'autoplot.R'
                              'axis-secondary.R' 'backports.R'
                              'bench.R' 'bin.R' 'coord-.R'
                              'coord-cartesian-.R' 'coord-fixed.R'
                              'coord-flip.R' 'coord-map.R'
                              'coord-munch.R' 'coord-polar.R'
                              'coord-quickmap.R' 'coord-radial.R'
                              'coord-sf.R' 'coord-transform.R' 'data.R'
                              'docs_layer.R' 'facet-.R' 'facet-grid-.R'
                              'facet-null.R' 'facet-wrap.R'
                              'fortify-map.R' 'fortify-models.R'
                              'fortify-spatial.R' 'fortify.R' 'stat-.R'
                              'geom-abline.R' 'geom-rect.R'
                              'geom-bar.R' 'geom-tile.R' 'geom-bin2d.R'
                              'geom-blank.R' 'geom-boxplot.R'
                              'geom-col.R' 'geom-path.R'
                              'geom-contour.R' 'geom-point.R'
                              'geom-count.R' 'geom-crossbar.R'
                              'geom-segment.R' 'geom-curve.R'
                              'geom-defaults.R' 'geom-ribbon.R'
                              'geom-density.R' 'geom-density2d.R'
                              'geom-dotplot.R' 'geom-errorbar.R'
                              'geom-freqpoly.R' 'geom-function.R'
                              'geom-hex.R' 'geom-histogram.R'
                              'geom-hline.R' 'geom-jitter.R'
                              'geom-label.R' 'geom-linerange.R'
                              'geom-pointrange.R' 'geom-quantile.R'
                              'geom-rug.R' 'geom-sf.R' 'geom-smooth.R'
                              'geom-spoke.R' 'geom-text.R'
                              'geom-violin.R' 'geom-vline.R'
                              'ggplot2-package.R' 'grob-absolute.R'
                              'grob-dotstack.R' 'grob-null.R'
                              'grouping.R' 'properties.R' 'margins.R'
                              'theme-elements.R' 'guide-.R'
                              'guide-axis.R' 'guide-axis-logticks.R'
                              'guide-axis-stack.R' 'guide-axis-theta.R'
                              'guide-legend.R' 'guide-bins.R'
                              'guide-colorbar.R' 'guide-colorsteps.R'
                              'guide-custom.R' 'guide-none.R'
                              'guide-old.R' 'guides-.R' 'guides-grid.R'
                              'hexbin.R' 'import-standalone-obj-type.R'
                              'import-standalone-types-check.R'
                              'labeller.R' 'labels.R' 'layer-sf.R'
                              'layout.R' 'limits.R' 'performance.R'
                              'plot-build.R' 'plot-construction.R'
                              'plot-last.R' 'plot.R' 'position-.R'
                              'position-collide.R' 'position-dodge.R'
                              'position-dodge2.R' 'position-identity.R'
                              'position-jitter.R'
                              'position-jitterdodge.R'
                              'position-nudge.R' 'position-stack.R'
                              'quick-plot.R' 'reshape-add-margins.R'
                              'save.R' 'scale-.R' 'scale-alpha.R'
                              'scale-binned.R' 'scale-brewer.R'
                              'scale-colour.R' 'scale-continuous.R'
                              'scale-date.R' 'scale-discrete-.R'
                              'scale-expansion.R' 'scale-gradient.R'
                              'scale-grey.R' 'scale-hue.R'
                              'scale-identity.R' 'scale-linetype.R'
                              'scale-linewidth.R' 'scale-manual.R'
                              'scale-shape.R' 'scale-size.R'
                              'scale-steps.R' 'scale-view.R'
                              'scale-viridis.R' 'scales-.R'
                              'stat-align.R' 'stat-bin.R'
                              'stat-summary-2d.R' 'stat-bin2d.R'
                              'stat-bindot.R' 'stat-binhex.R'
                              'stat-boxplot.R' 'stat-connect.R'
                              'stat-contour.R' 'stat-count.R'
                              'stat-density-2d.R' 'stat-density.R'
                              'stat-ecdf.R' 'stat-ellipse.R'
                              'stat-function.R' 'stat-identity.R'
                              'stat-manual.R' 'stat-qq-line.R'
                              'stat-qq.R' 'stat-quantilemethods.R'
                              'stat-sf-coordinates.R' 'stat-sf.R'
                              'stat-smooth-methods.R' 'stat-smooth.R'
                              'stat-sum.R' 'stat-summary-bin.R'
                              'stat-summary-hex.R' 'stat-summary.R'
                              'stat-unique.R' 'stat-ydensity.R'
                              'summarise-plot.R' 'summary.R' 'theme.R'
                              'theme-defaults.R' 'theme-current.R'
                              'theme-sub.R' 'utilities-break.R'
                              'utilities-grid.R' 'utilities-help.R'
                              'utilities-patterns.R'
                              'utilities-resolution.R'
                              'utilities-tidy-eval.R' 'zxx.R' 'zzz.R'
NeedsCompilation:             no
Packaged:                     2025-11-13 07:39:29 UTC; thomas
Author:                       Hadley Wickham [aut] (ORCID:
                              <https://orcid.org/0000-0003-4757-117X>),
                              Winston Chang [aut] (ORCID:
                              <https://orcid.org/0000-0002-1576-2126>),
                              Lionel Henry [aut], Thomas Lin Pedersen
                              [aut, cre] (ORCID:
                              <https://orcid.org/0000-0002-5147-4711>),
                              Kohske Takahashi [aut], Claus Wilke [aut]
                              (ORCID:
                              <https://orcid.org/0000-0002-7470-9261>),
                              Kara Woo [aut] (ORCID:
                              <https://orcid.org/0000-0002-5125-4188>),
                              Hiroaki Yutani [aut] (ORCID:
                              <https://orcid.org/0000-0002-3385-7233>),
                              Dewey Dunnington [aut] (ORCID:
                              <https://orcid.org/0000-0002-9415-4582>),
                              Teun van den Brand [aut] (ORCID:
                              <https://orcid.org/0000-0002-9335-7468>),
                              Posit, PBC [cph, fnd] (ROR:
                              <https://ror.org/03wc8by49>)
Maintainer:                   Thomas Lin Pedersen
                              <thomas.pedersen@posit.co>
Repository:                   CRAN
Date/Publication:             2025-11-14 09:20:02 UTC
Built:                        R 4.5.2; ; 2025-12-30 02:47:02 UTC;
                              windows

Index:

CoordSf                 Visualise sf objects
add_gg                  Add components to a plot
aes                     Construct aesthetic mappings
aes_colour_fill_alpha   Colour related aesthetics: colour, fill, and
                        alpha
aes_eval                Control aesthetic evaluation
aes_group_order         Aesthetics: grouping
aes_linetype_size_shape
                        Differentiation related aesthetics: linetype,
                        size, shape
aes_position            Position related aesthetics: x, y, xmin, xmax,
                        ymin, ymax, xend, yend
annotate                Create an annotation layer
annotation_borders      Create a layer of map borders
annotation_custom       Annotation: Custom grob
annotation_logticks     Annotation: log tick marks
annotation_map          Annotation: a map
annotation_raster       Annotation: high-performance rectangular tiling
autolayer               Create a ggplot layer appropriate to a
                        particular data type
automatic_plotting      Tailoring plots to particular data types
autoplot                Create a complete ggplot appropriate to a
                        particular data type
coord_cartesian         Cartesian coordinates
coord_fixed             Cartesian coordinates with fixed "aspect ratio"
coord_flip              Cartesian coordinates with x and y flipped
coord_map               Map projections
coord_polar             Polar coordinates
coord_transform         Transformed Cartesian coordinate system
cut_interval            Discretise numeric data into categorical
diamonds                Prices of over 50,000 round cut diamonds
draw_key                Key glyphs for legends
economics               US economic time series
expand_limits           Expand the plot limits, using data
expansion               Generate expansion vector for scales
facet_grid              Lay out panels in a grid
facet_wrap              Wrap a 1d ribbon of panels into 2d
faithfuld               2d density estimate of Old Faithful data
fortify                 Fortify a model with data.
geom_abline             Reference lines: horizontal, vertical, and
                        diagonal
geom_bar                Bar charts
geom_bin_2d             Heatmap of 2d bin counts
geom_blank              Draw nothing
geom_boxplot            A box and whiskers plot (in the style of Tukey)
geom_contour            2D contours of a 3D surface
geom_count              Count overlapping points
geom_crossbar           Vertical intervals: lines, crossbars &
                        errorbars
geom_density            Smoothed density estimates
geom_density_2d         Contours of a 2D density estimate
geom_dotplot            Dot plot
geom_freqpoly           Histograms and frequency polygons
geom_function           Draw a function as a continuous curve
geom_hex                Hexagonal heatmap of 2d bin counts
geom_jitter             Jittered points
geom_label              Text
geom_map                Polygons from a reference map
geom_path               Connect observations
geom_point              Points
geom_polygon            Polygons
geom_qq_line            A quantile-quantile plot
geom_quantile           Quantile regression
geom_raster             Rectangles
geom_ribbon             Ribbons and area plots
geom_rug                Rug plots in the margins
geom_segment            Line segments and curves
geom_smooth             Smoothed conditional means
geom_spoke              Line segments parameterised by location,
                        direction and distance
geom_violin             Violin plot
get_alt_text            Extract alt text from a plot
get_theme               Get, set, and modify the active theme
ggplot                  Create a new ggplot
ggproto                 Create a new ggproto object
ggsave                  Save a ggplot (or other grid object) with
                        sensible defaults
guide_axis              Axis guide
guide_axis_logticks     Axis with logarithmic tick marks
guide_axis_stack        Stacked axis guides
guide_axis_theta        Angle axis guide
guide_bins              A binned version of guide_legend
guide_colourbar         Continuous colour bar guide
guide_coloursteps       Discretized colourbar guide
guide_custom            Custom guides
guide_legend            Legend guide
guide_none              Empty guide
guides                  Set guides for each scale
hmisc                   A selection of summary functions from Hmisc
label_bquote            Label with mathematical expressions
labeller                Construct labelling specification
labellers               Useful labeller functions
labs                    Modify axis, legend, and plot labels
layer_geoms             Layer geometry display
layer_positions         Layer position adjustments
layer_stats             Layer statistical transformations
lims                    Set scale limits
luv_colours             'colors()' in Luv space
margin                  Theme elements
mean_se                 Calculate mean and standard error of the mean
midwest                 Midwest demographics
mpg                     Fuel economy data from 1999 to 2008 for 38
                        popular models of cars
msleep                  An updated and expanded version of the mammals
                        sleep dataset
position_dodge          Dodge overlapping objects side-to-side
position_identity       Don't adjust position
position_jitter         Jitter points to avoid overplotting
position_jitterdodge    Simultaneously dodge and jitter
position_nudge          Nudge points a fixed distance
position_stack          Stack overlapping objects on top of each
                        another
presidential            Terms of 12 presidents from Eisenhower to Trump
print.ggplot            Explicitly draw plot
print.ggproto           Format or print a ggproto object
qplot                   Quick plot
resolution              Compute the "resolution" of a numeric vector
scale_alpha             Alpha transparency scales
scale_colour_brewer     Sequential, diverging and qualitative colour
                        scales from ColorBrewer
scale_colour_continuous
                        Continuous and binned colour scales
scale_colour_discrete   Discrete colour scales
scale_colour_gradient   Gradient colour scales
scale_colour_grey       Sequential grey colour scales
scale_colour_hue        Evenly spaced colours for discrete data
scale_colour_identity   Use values without scaling
scale_colour_manual     Create your own discrete scale
scale_colour_steps      Binned gradient colour scales
scale_colour_viridis_d
                        Viridis colour scales from viridisLite
scale_linetype          Scale for line patterns
scale_linewidth         Scales for line width
scale_shape             Scales for shapes, aka glyphs
scale_size              Scales for area or radius
scale_x_binned          Positional scales for binning continuous data
                        (x & y)
scale_x_continuous      Position scales for continuous data (x & y)
scale_x_date            Position scales for date/time data
scale_x_discrete        Position scales for discrete data
seals                   Vector field of seal movements
sec_axis                Specify a secondary axis
stat_connect            Connect observations
stat_ecdf               Compute empirical cumulative distribution
stat_ellipse            Compute normal data ellipses
stat_identity           Leave data as is
stat_manual             Manually compute transformations
stat_sf_coordinates     Extract coordinates from 'sf' objects
stat_summary_2d         Bin and summarise in 2d (rectangle & hexagons)
stat_summary_bin        Summarise y values at unique/binned x
stat_unique             Remove duplicates
subtheme                Shortcuts for theme settings
theme                   Modify components of a theme
theme_grey              Complete themes
txhousing               Housing sales in TX
vars                    Quote faceting variables


:

## 6. Session Info

It's good practice to record your R session information at the end of your analysis. This helps with reproducibility by documenting:
- R version
- Operating system
- Loaded packages and their versions
- Other system details

In [ ]:
sessionInfo()